[package]
name = "server_data_profile"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-stack = { workspace = true }

model_profile = { path = "../model_profile" }
server_common = { path = "../server_common" }
server_data = { path = "../server_data" }

database = { path = "../database" }
database_profile = { path = "../database_profile" }

simple_backend = { path = "../simple_backend" }
simple_backend_model = { path = "../simple_backend_model" }
