[package]
name = "server_data_all"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
zip = { workspace = true }
num_cpus = { workspace = true }

axum = { workspace = true }

error-stack = { workspace = true }

config = { path = "../config" }
model = { path = "../model" }
model_account = { path = "../model_account" }
model_profile = { path = "../model_profile" }
model_media = { path = "../model_media" }
model_chat = { path = "../model_chat" }
server_common = { path = "../server_common" }

server_data = { path = "../server_data" }
server_data_account = { path = "../server_data_account" }
server_data_profile = { path = "../server_data_profile" }
server_data_chat = { path = "../server_data_chat" }
server_data_media = { path = "../server_data_media" }

database = { path = "../database" }
database_account = { path = "../database_account" }
database_profile = { path = "../database_profile" }
database_media = { path = "../database_media" }
database_chat = { path = "../database_chat" }

simple_backend = { path = "../simple_backend" }
